name: CI/CD - House Price App

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub (optional)
      if: false  # set to true if pushing image to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t house-price-app .

    - name: (Optional) Run tests
      run: echo "Add test script here"

    - name: (Optional) Run Docker container
      run: echo "Use cloud deployment or manual run on server"

